// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GraduationProject.Models;

public partial class dbFurniMartContext : DbContext
{
    public dbFurniMartContext(DbContextOptions<dbFurniMartContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TAccount> TAccounts { get; set; }

    public virtual DbSet<TBrowsingHistory> TBrowsingHistories { get; set; }

    public virtual DbSet<TCart> TCarts { get; set; }

    public virtual DbSet<TCartItem> TCartItems { get; set; }

    public virtual DbSet<TCategory> TCategories { get; set; }

    public virtual DbSet<TChatRoom> TChatRooms { get; set; }

    public virtual DbSet<TCheckinRecord> TCheckinRecords { get; set; }

    public virtual DbSet<TColor> TColors { get; set; }

    public virtual DbSet<TColorOptionTexture> TColorOptionTextures { get; set; }

    public virtual DbSet<TContactForm> TContactForms { get; set; }

    public virtual DbSet<TCustomer> TCustomers { get; set; }

    public virtual DbSet<TDeliveryStatus> TDeliveryStatuses { get; set; }

    public virtual DbSet<TEmployee> TEmployees { get; set; }

    public virtual DbSet<TEmployeePasswordReset> TEmployeePasswordResets { get; set; }

    public virtual DbSet<TEmployeeRole> TEmployeeRoles { get; set; }

    public virtual DbSet<TEmployeeStatus> TEmployeeStatuses { get; set; }

    public virtual DbSet<TGender> TGenders { get; set; }

    public virtual DbSet<TLeave> TLeaves { get; set; }

    public virtual DbSet<TLevel> TLevels { get; set; }

    public virtual DbSet<TLike> TLikes { get; set; }

    public virtual DbSet<TLogisticsProvider> TLogisticsProviders { get; set; }

    public virtual DbSet<TMaterial> TMaterials { get; set; }

    public virtual DbSet<TMember> TMembers { get; set; }

    public virtual DbSet<TMessage> TMessages { get; set; }

    public virtual DbSet<TModel> TModels { get; set; }

    public virtual DbSet<TOrder> TOrders { get; set; }

    public virtual DbSet<TOrderDetail> TOrderDetails { get; set; }

    public virtual DbSet<TOrderStatus> TOrderStatuses { get; set; }

    public virtual DbSet<TOrderStatusHistory> TOrderStatusHistories { get; set; }

    public virtual DbSet<TPartColorOption> TPartColorOptions { get; set; }

    public virtual DbSet<TPaymentMethod> TPaymentMethods { get; set; }

    public virtual DbSet<TPaymentStatus> TPaymentStatuses { get; set; }

    public virtual DbSet<TPickupMethod> TPickupMethods { get; set; }

    public virtual DbSet<TProduct> TProducts { get; set; }

    public virtual DbSet<TProductAsset> TProductAssets { get; set; }

    public virtual DbSet<TProductPart> TProductParts { get; set; }

    public virtual DbSet<TProductReview> TProductReviews { get; set; }

    public virtual DbSet<TProductVariant> TProductVariants { get; set; }

    public virtual DbSet<TPstatus> TPstatuses { get; set; }

    public virtual DbSet<TRequestStatus> TRequestStatuses { get; set; }

    public virtual DbSet<TResponse> TResponses { get; set; }

    public virtual DbSet<TSalary> TSalaries { get; set; }

    public virtual DbSet<TStatus> TStatuses { get; set; }

    public virtual DbSet<TTexture> TTextures { get; set; }

    public virtual DbSet<TTimesheet> TTimesheets { get; set; }

    public virtual DbSet<TTimesheetStatus> TTimesheetStatuses { get; set; }

    public virtual DbSet<TWorkDaily> TWorkDailies { get; set; }

    public virtual DbSet<TmessageTemplate> TmessageTemplates { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TAccount>(entity =>
        {
            entity.HasKey(e => e.FAccountId);

            entity.ToTable("tAccount");

            entity.Property(e => e.FAccountId).HasColumnName("fAccountId");
            entity.Property(e => e.FCreatTime)
                .HasColumnType("datetime")
                .HasColumnName("fCreatTime");
            entity.Property(e => e.FEmail)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("fEmail");
            entity.Property(e => e.FEmailVerifiedTime)
                .HasColumnType("datetime")
                .HasColumnName("fEmailVerifiedTime");
            entity.Property(e => e.FLastLoginTime)
                .HasColumnType("datetime")
                .HasColumnName("fLastLoginTime");
            entity.Property(e => e.FLoginFailureCount).HasColumnName("fLoginFailureCount");
            entity.Property(e => e.FMemberId).HasColumnName("fMemberId");
            entity.Property(e => e.FPasswordFinal)
                .HasMaxLength(100)
                .HasColumnName("fPasswordFinal");
            entity.Property(e => e.FPasswordSalt)
                .HasMaxLength(100)
                .HasColumnName("fPasswordSalt");
            entity.Property(e => e.FProvider)
                .HasMaxLength(50)
                .HasColumnName("fProvider");
            entity.Property(e => e.FProviderAccountKey)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("fProviderAccountKey");
            entity.Property(e => e.FUpdateTime)
                .HasColumnType("datetime")
                .HasColumnName("fUpdateTime");
        });

        modelBuilder.Entity<TBrowsingHistory>(entity =>
        {
            entity.HasKey(e => e.FBrowsingHistoryId);

            entity.ToTable("tBrowsingHistory");

            entity.Property(e => e.FBrowsingHistoryId).HasColumnName("fBrowsingHistoryId");
            entity.Property(e => e.FBrowsingTime)
                .HasColumnType("datetime")
                .HasColumnName("fBrowsingTime");
            entity.Property(e => e.FMemderId).HasColumnName("fMemderId");
            entity.Property(e => e.FProductId).HasColumnName("fProductId");
        });

        modelBuilder.Entity<TCart>(entity =>
        {
            entity.HasKey(e => e.FCartId).HasName("PK_tShoppingCart");

            entity.ToTable("tCart");

            entity.Property(e => e.FCartId).HasColumnName("fCartId");
            entity.Property(e => e.FDate)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("fDate");
            entity.Property(e => e.FIsCheckOut).HasColumnName("fIsCheckOut");
            entity.Property(e => e.FIsDeleted).HasColumnName("fIsDeleted");
            entity.Property(e => e.FMemberId).HasColumnName("fMemberId");
            entity.Property(e => e.FTotalPrice)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("fTotalPrice");
        });

        modelBuilder.Entity<TCartItem>(entity =>
        {
            entity.HasKey(e => e.FCartItemId);

            entity.ToTable("tCartItem");

            entity.Property(e => e.FCartItemId).HasColumnName("fCartItemId");
            entity.Property(e => e.FCartId).HasColumnName("fCartId");
            entity.Property(e => e.FIsDeleted).HasColumnName("fIsDeleted");
            entity.Property(e => e.FProductVariantId).HasColumnName("fProductVariantId");
            entity.Property(e => e.FQuantity).HasColumnName("fQuantity");
            entity.Property(e => e.FSubtotal)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("fSubtotal");
            entity.Property(e => e.FUnitPrice)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("fUnitPrice");
        });

        modelBuilder.Entity<TCategory>(entity =>
        {
            entity.HasKey(e => e.FCategoryId).HasName("PK__tCategor__53E607B3093FC123");

            entity.ToTable("tCategory");

            entity.Property(e => e.FCategoryId).HasColumnName("fCategoryId");
            entity.Property(e => e.FCreateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fCreateTime");
            entity.Property(e => e.FDescription)
                .HasMaxLength(500)
                .HasColumnName("fDescription");
            entity.Property(e => e.FImageUrl)
                .HasMaxLength(500)
                .HasColumnName("fImageUrl");
            entity.Property(e => e.FIsActive).HasColumnName("fIsActive");
            entity.Property(e => e.FName)
                .HasMaxLength(50)
                .HasColumnName("fName");
            entity.Property(e => e.FParentCategoryId).HasColumnName("fParentCategoryId");
            entity.Property(e => e.FSortOrder).HasColumnName("fSortOrder");
            entity.Property(e => e.FUpdateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fUpdateTime");
        });

        modelBuilder.Entity<TChatRoom>(entity =>
        {
            entity.HasKey(e => e.FChatRoomId);

            entity.ToTable("tChatRoom");

            entity.Property(e => e.FChatRoomId).HasColumnName("fChatRoomId");
            entity.Property(e => e.FBotStateJson).HasColumnName("fBotStateJson");
            entity.Property(e => e.FChannel)
                .HasMaxLength(30)
                .HasColumnName("fChannel");
            entity.Property(e => e.FClosedAt)
                .HasColumnType("datetime")
                .HasColumnName("fClosedAt");
            entity.Property(e => e.FCreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("fCreatedAt");
            entity.Property(e => e.FEmployeeId).HasColumnName("fEmployeeId");
            entity.Property(e => e.FFirstMessageAt)
                .HasColumnType("datetime")
                .HasColumnName("fFirstMessageAt");
            entity.Property(e => e.FIsBotActive).HasColumnName("fIsBotActive");
            entity.Property(e => e.FLastMessageAt)
                .HasColumnType("datetime")
                .HasColumnName("fLastMessageAt");
            entity.Property(e => e.FMemberId).HasColumnName("fMemberId");
            entity.Property(e => e.FStatus)
                .HasMaxLength(20)
                .HasColumnName("fStatus");
            entity.Property(e => e.FVisitorKey)
                .HasMaxLength(60)
                .HasColumnName("fVisitorKey");
        });

        modelBuilder.Entity<TCheckinRecord>(entity =>
        {
            entity.HasKey(e => e.FCheckinRecordId);

            entity.ToTable("tCheckinRecord");

            entity.Property(e => e.FCheckinRecordId).HasColumnName("fCheckinRecordId");
            entity.Property(e => e.FCheckinTime)
                .HasColumnType("datetime")
                .HasColumnName("fCheckinTime");
            entity.Property(e => e.FEmployeeId).HasColumnName("fEmployeeId");
            entity.Property(e => e.FIpAddress)
                .HasMaxLength(45)
                .HasColumnName("fIpAddress");
            entity.Property(e => e.FItem)
                .HasMaxLength(10)
                .HasColumnName("fItem");
            entity.Property(e => e.FLatitude)
                .HasColumnType("decimal(9, 6)")
                .HasColumnName("fLatitude");
            entity.Property(e => e.FLongitude)
                .HasColumnType("decimal(9, 6)")
                .HasColumnName("fLongitude");
            entity.Property(e => e.FRediusMeters).HasColumnName("fRediusMeters");
            entity.Property(e => e.FRemark)
                .HasMaxLength(200)
                .HasColumnName("fRemark");
        });

        modelBuilder.Entity<TColor>(entity =>
        {
            entity.HasKey(e => e.FColorId).HasName("PK__tColor__7107245520CFA312");

            entity.ToTable("tColor");

            entity.Property(e => e.FColorId).HasColumnName("fColorId");
            entity.Property(e => e.FColorCode)
                .HasMaxLength(6)
                .IsUnicode(false)
                .HasColumnName("fColorCode");
            entity.Property(e => e.FColorName)
                .HasMaxLength(30)
                .HasColumnName("fColorName");
        });

        modelBuilder.Entity<TColorOptionTexture>(entity =>
        {
            entity.HasKey(e => e.FTextureId).HasName("PK__tColorOp__8DAFFC86F79F10CE");

            entity.ToTable("tColorOptionTexture");

            entity.Property(e => e.FTextureId).HasColumnName("fTextureId");
            entity.Property(e => e.FColorOptionId).HasColumnName("fColorOptionId");
            entity.Property(e => e.FFilePath)
                .HasMaxLength(500)
                .HasColumnName("fFilePath");
            entity.Property(e => e.FTextureType)
                .HasMaxLength(20)
                .HasColumnName("fTextureType");
            entity.Property(e => e.FTiling)
                .HasMaxLength(20)
                .HasDefaultValue("1,1")
                .HasColumnName("fTiling");
        });

        modelBuilder.Entity<TContactForm>(entity =>
        {
            entity.HasKey(e => e.FContactFormsId).HasName("PK_tContactForms");

            entity.ToTable("tContactForm");

            entity.Property(e => e.FContactFormsId).HasColumnName("fContactFormsId");
            entity.Property(e => e.FChatRoomId).HasColumnName("fChatRoomId");
            entity.Property(e => e.FCompanyName)
                .HasMaxLength(200)
                .HasColumnName("fCompanyName");
            entity.Property(e => e.FContactName)
                .HasMaxLength(100)
                .HasColumnName("fContactName");
            entity.Property(e => e.FCreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("fCreatedAt");
            entity.Property(e => e.FEmail)
                .HasMaxLength(255)
                .HasColumnName("fEmail");
            entity.Property(e => e.FExtra).HasColumnName("fExtra");
            entity.Property(e => e.FMemberId).HasColumnName("fMemberId");
            entity.Property(e => e.FPhone)
                .HasMaxLength(50)
                .HasColumnName("fPhone");
            entity.Property(e => e.FRegion)
                .HasMaxLength(100)
                .HasColumnName("fRegion");
            entity.Property(e => e.FSubject)
                .HasMaxLength(255)
                .HasColumnName("fSubject");
        });

        modelBuilder.Entity<TCustomer>(entity =>
        {
            entity.HasKey(e => e.FId);

            entity.ToTable("tCustomer");

            entity.Property(e => e.FId).HasColumnName("fId");
            entity.Property(e => e.FAddress)
                .HasMaxLength(50)
                .HasColumnName("fAddress");
            entity.Property(e => e.FEmail)
                .HasMaxLength(50)
                .HasColumnName("fEmail");
            entity.Property(e => e.FName)
                .HasMaxLength(50)
                .HasColumnName("fName");
            entity.Property(e => e.FPassword)
                .HasMaxLength(50)
                .HasColumnName("fPassword");
            entity.Property(e => e.FPhone)
                .HasMaxLength(50)
                .HasColumnName("fPhone");
        });

        modelBuilder.Entity<TDeliveryStatus>(entity =>
        {
            entity.HasKey(e => e.FDeliveryStatus).HasName("PK__tDeliver__D6E794C0617ED6C5");

            entity.ToTable("tDeliveryStatus");

            entity.Property(e => e.FDeliveryStatus).HasColumnName("fDeliveryStatus");
            entity.Property(e => e.FDeliveryStatusName)
                .IsRequired()
                .HasMaxLength(15)
                .HasColumnName("fDeliveryStatusName");
        });

        modelBuilder.Entity<TEmployee>(entity =>
        {
            entity.HasKey(e => e.FEmployeeId).HasName("PK_tEmployees");

            entity.ToTable("tEmployee");

            entity.Property(e => e.FEmployeeId).HasColumnName("fEmployeeID");
            entity.Property(e => e.FAccount)
                .HasMaxLength(20)
                .HasColumnName("fAccount");
            entity.Property(e => e.FBloodType)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("fBloodType");
            entity.Property(e => e.FChangePasswordTime)
                .HasColumnType("datetime")
                .HasColumnName("fChangePasswordTime");
            entity.Property(e => e.FEmail)
                .HasMaxLength(30)
                .HasColumnName("fEmail");
            entity.Property(e => e.FGender).HasColumnName("fGender");
            entity.Property(e => e.FHeadShot)
                .HasMaxLength(50)
                .HasColumnName("fHeadShot");
            entity.Property(e => e.FHireDate)
                .HasColumnType("datetime")
                .HasColumnName("fHireDate");
            entity.Property(e => e.FLoginTime)
                .HasColumnType("datetime")
                .HasColumnName("fLoginTime");
            entity.Property(e => e.FName)
                .HasMaxLength(50)
                .HasColumnName("fName");
            entity.Property(e => e.FPasswords)
                .HasMaxLength(500)
                .HasColumnName("fPasswords");
            entity.Property(e => e.FPhone)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("fPhone");
            entity.Property(e => e.FRoleId).HasColumnName("fRoleId");
            entity.Property(e => e.FStatusId).HasColumnName("fStatusId");
        });

        modelBuilder.Entity<TEmployeePasswordReset>(entity =>
        {
            entity.HasKey(e => e.FResetId).HasName("PK__tEmploye__11AED4F18F98AC5C");

            entity.ToTable("tEmployeePasswordReset");

            entity.Property(e => e.FResetId).HasColumnName("fResetId");
            entity.Property(e => e.FCreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("fCreatedAt");
            entity.Property(e => e.FEmployeeId).HasColumnName("fEmployeeID");
            entity.Property(e => e.FExpiresAt)
                .HasColumnType("datetime")
                .HasColumnName("fExpiresAt");
            entity.Property(e => e.FToken)
                .HasMaxLength(100)
                .HasColumnName("fToken");
            entity.Property(e => e.FUsedAt)
                .HasColumnType("datetime")
                .HasColumnName("fUsedAt");
        });

        modelBuilder.Entity<TEmployeeRole>(entity =>
        {
            entity.HasKey(e => e.FRoleId).HasName("PK_tEmployeesRole");

            entity.ToTable("tEmployeeRole");

            entity.Property(e => e.FRoleId).HasColumnName("fRoleId");
            entity.Property(e => e.FRoleClass)
                .HasMaxLength(20)
                .HasColumnName("fRoleClass");
        });

        modelBuilder.Entity<TEmployeeStatus>(entity =>
        {
            entity.HasKey(e => e.FStatusId).HasName("PK_tEmployeesStatus");

            entity.ToTable("tEmployeeStatus");

            entity.Property(e => e.FStatusId).HasColumnName("fStatusId");
            entity.Property(e => e.FStatus)
                .HasMaxLength(10)
                .HasColumnName("fStatus");
        });

        modelBuilder.Entity<TGender>(entity =>
        {
            entity.HasKey(e => e.FGenderId).HasName("PK_TGender");

            entity.ToTable("tGender");

            entity.Property(e => e.FGenderId).HasColumnName("fGenderId");
            entity.Property(e => e.FGenderName)
                .HasMaxLength(50)
                .HasColumnName("fGenderName");
        });

        modelBuilder.Entity<TLeave>(entity =>
        {
            entity.HasKey(e => e.FLeaveId);

            entity.ToTable("tLeave");

            entity.Property(e => e.FLeaveId).HasColumnName("fLeaveId");
            entity.Property(e => e.FCreatetime)
                .HasColumnType("datetime")
                .HasColumnName("fCreatetime");
            entity.Property(e => e.FDescription)
                .HasMaxLength(200)
                .HasColumnName("fDescription");
            entity.Property(e => e.FEmployeeId).HasColumnName("fEmployeeId");
            entity.Property(e => e.FEndDate)
                .HasColumnType("datetime")
                .HasColumnName("fEndDate");
            entity.Property(e => e.FLeaveType)
                .HasMaxLength(20)
                .HasColumnName("fLeaveType");
            entity.Property(e => e.FPicture)
                .HasMaxLength(30)
                .HasColumnName("fPicture");
            entity.Property(e => e.FStartDate)
                .HasColumnType("datetime")
                .HasColumnName("fStartDate");
            entity.Property(e => e.FStatusId).HasColumnName("fStatusId");
        });

        modelBuilder.Entity<TLevel>(entity =>
        {
            entity.HasKey(e => e.FLevelId);

            entity.ToTable("tLevel");

            entity.Property(e => e.FLevelId).HasColumnName("fLevelId");
            entity.Property(e => e.FDiscount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("fDiscount");
            entity.Property(e => e.FLevelName)
                .HasMaxLength(50)
                .HasColumnName("fLevelName");
            entity.Property(e => e.FUpgradeRules)
                .HasMaxLength(50)
                .HasColumnName("fUpgradeRules");
        });

        modelBuilder.Entity<TLike>(entity =>
        {
            entity.HasKey(e => e.FLikeId);

            entity.ToTable("tLike");

            entity.Property(e => e.FLikeId).HasColumnName("fLikeId");
            entity.Property(e => e.FAddTime)
                .HasColumnType("datetime")
                .HasColumnName("fAddTime");
            entity.Property(e => e.FMemberId).HasColumnName("fMemberId");
            entity.Property(e => e.FProductVariantId).HasColumnName("fProductVariantId");
        });

        modelBuilder.Entity<TLogisticsProvider>(entity =>
        {
            entity.HasKey(e => e.FLogisticsProvider);

            entity.ToTable("tLogisticsProvider");

            entity.Property(e => e.FLogisticsProvider).HasColumnName("fLogisticsProvider");
            entity.Property(e => e.FLogisticsProviderName)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("fLogisticsProviderName");
        });

        modelBuilder.Entity<TMaterial>(entity =>
        {
            entity.HasKey(e => e.FMaterialId).HasName("PK__tMateria__C6A05347061F462C");

            entity.ToTable("tMaterial");

            entity.Property(e => e.FMaterialId).HasColumnName("fMaterialId");
            entity.Property(e => e.FDescription)
                .HasMaxLength(500)
                .HasColumnName("fDescription");
            entity.Property(e => e.FMarterialName)
                .HasMaxLength(30)
                .HasColumnName("fMarterialName");
        });

        modelBuilder.Entity<TMember>(entity =>
        {
            entity.HasKey(e => e.FMemberId);

            entity.ToTable("tMember");

            entity.Property(e => e.FMemberId).HasColumnName("fMemberId");
            entity.Property(e => e.FAccount)
                .HasMaxLength(20)
                .HasColumnName("fAccount");
            entity.Property(e => e.FAddress)
                .HasMaxLength(150)
                .HasColumnName("fAddress");
            entity.Property(e => e.FBirthDate).HasColumnName("fBirthDate");
            entity.Property(e => e.FCreatTime)
                .HasColumnType("datetime")
                .HasColumnName("fCreatTime");
            entity.Property(e => e.FDisplayName)
                .HasMaxLength(50)
                .HasColumnName("fDisplayName");
            entity.Property(e => e.FEmail)
                .HasMaxLength(150)
                .HasColumnName("fEmail");
            entity.Property(e => e.FEmailState).HasColumnName("fEmailState");
            entity.Property(e => e.FGender).HasColumnName("fGender");
            entity.Property(e => e.FLeveId).HasColumnName("fLeveId");
            entity.Property(e => e.FMemberImage)
                .HasMaxLength(100)
                .HasColumnName("fMemberImage");
            entity.Property(e => e.FMoneySum).HasColumnName("fMoneySum");
            entity.Property(e => e.FName)
                .HasMaxLength(50)
                .HasColumnName("fName");
            entity.Property(e => e.FPasswords)
                .HasMaxLength(500)
                .HasColumnName("fPasswords");
            entity.Property(e => e.FPhone)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("fPhone");
            entity.Property(e => e.FPhoneState).HasColumnName("fPhoneState");
            entity.Property(e => e.FStatus).HasColumnName("fStatus");
            entity.Property(e => e.FUpdateTime)
                .HasColumnType("datetime")
                .HasColumnName("fUpdateTime");
        });

        modelBuilder.Entity<TMessage>(entity =>
        {
            entity.HasKey(e => e.FMessagesId).HasName("PK_tMessages");

            entity.ToTable("tMessage");

            entity.Property(e => e.FMessagesId).HasColumnName("fMessagesId");
            entity.Property(e => e.FChatRoomId).HasColumnName("fChatRoomId");
            entity.Property(e => e.FContent).HasColumnName("fContent");
            entity.Property(e => e.FContentJson).HasColumnName("fContentJson");
            entity.Property(e => e.FContentType)
                .HasMaxLength(20)
                .HasColumnName("fContentType");
            entity.Property(e => e.FCreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("fCreatedAt");
            entity.Property(e => e.FMetaJson).HasColumnName("fMetaJson");
            entity.Property(e => e.FParentMessageId).HasColumnName("fParentMessageId");
            entity.Property(e => e.FSenderId)
                .HasMaxLength(10)
                .HasColumnName("fSenderId");
            entity.Property(e => e.FSenderType)
                .HasMaxLength(20)
                .HasColumnName("fSenderType");
        });

        modelBuilder.Entity<TModel>(entity =>
        {
            entity.HasKey(e => e.FModelId).HasName("PK__tModel__58EC54A1EFEF7887");

            entity.ToTable("tModel");

            entity.Property(e => e.FModelId).HasColumnName("fModelId");
            entity.Property(e => e.FModelName)
                .HasMaxLength(30)
                .HasColumnName("fModelName");
            entity.Property(e => e.FModelUrl)
                .HasMaxLength(500)
                .HasColumnName("fModelUrl");
        });

        modelBuilder.Entity<TOrder>(entity =>
        {
            entity.HasKey(e => e.FOrderId);

            entity.ToTable("tOrder");

            entity.Property(e => e.FOrderId).HasColumnName("fOrderId");
            entity.Property(e => e.FDeliveryAddress)
                .HasMaxLength(100)
                .HasColumnName("fDeliveryAddress");
            entity.Property(e => e.FDeliveryStatus).HasColumnName("fDeliveryStatus");
            entity.Property(e => e.FDeliveryTime)
                .HasColumnType("datetime")
                .HasColumnName("fDeliveryTime");
            entity.Property(e => e.FDiscount)
                .HasColumnType("decimal(4, 2)")
                .HasColumnName("fDiscount");
            entity.Property(e => e.FEmployeeId).HasColumnName("fEmployeeId");
            entity.Property(e => e.FIsDeleted).HasColumnName("fIsDeleted");
            entity.Property(e => e.FLogisticsProvider).HasColumnName("fLogisticsProvider");
            entity.Property(e => e.FMemberId).HasColumnName("fMemberId");
            entity.Property(e => e.FNote)
                .HasMaxLength(1000)
                .HasColumnName("fNote");
            entity.Property(e => e.FOrderCompletionTime)
                .HasColumnType("datetime")
                .HasColumnName("fOrderCompletionTime");
            entity.Property(e => e.FOrderStatus).HasColumnName("fOrderStatus");
            entity.Property(e => e.FOrderTime)
                .HasColumnType("datetime")
                .HasColumnName("fOrderTime");
            entity.Property(e => e.FPaymentMethod).HasColumnName("fPaymentMethod");
            entity.Property(e => e.FPaymentStatus).HasColumnName("fPaymentStatus");
            entity.Property(e => e.FPaymentTime)
                .HasColumnType("datetime")
                .HasColumnName("fPaymentTime");
            entity.Property(e => e.FPickupMethod).HasColumnName("fPickupMethod");
            entity.Property(e => e.FShippingCost)
                .HasColumnType("decimal(7, 2)")
                .HasColumnName("fShippingCost");
            entity.Property(e => e.FTaxNo)
                .HasMaxLength(8)
                .IsUnicode(false)
                .HasColumnName("fTaxNo");
            entity.Property(e => e.FTotalPrice)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("fTotalPrice");
        });

        modelBuilder.Entity<TOrderDetail>(entity =>
        {
            entity.HasKey(e => new { e.FOrderId, e.FProductVariantId });

            entity.ToTable("tOrderDetail");

            entity.Property(e => e.FOrderId).HasColumnName("fOrderId");
            entity.Property(e => e.FProductVariantId).HasColumnName("fProductVariantId");
            entity.Property(e => e.FIsDeleted).HasColumnName("fIsDeleted");
            entity.Property(e => e.FQuantity).HasColumnName("fQuantity");
            entity.Property(e => e.FUnitPrice)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("fUnitPrice");
        });

        modelBuilder.Entity<TOrderStatus>(entity =>
        {
            entity.HasKey(e => e.FOrderStatus).HasName("PK__tOrderSt__D3DDFC1F1C093DB4");

            entity.ToTable("tOrderStatus");

            entity.Property(e => e.FOrderStatus).HasColumnName("fOrderStatus");
            entity.Property(e => e.FStatusName)
                .IsRequired()
                .HasMaxLength(15)
                .HasColumnName("fStatusName");
        });

        modelBuilder.Entity<TOrderStatusHistory>(entity =>
        {
            entity.HasKey(e => e.FHistoryId).HasName("PK_TOrderStatusHistory");

            entity.ToTable("tOrderStatusHistory");

            entity.Property(e => e.FHistoryId).HasColumnName("fHistoryId");
            entity.Property(e => e.FChangeTime)
                .HasColumnType("datetime")
                .HasColumnName("fChangeTime");
            entity.Property(e => e.FEmployeeId).HasColumnName("fEmployeeId");
            entity.Property(e => e.FOrderId).HasColumnName("fOrderId");
            entity.Property(e => e.FStatusId).HasColumnName("fStatusId");
        });

        modelBuilder.Entity<TPartColorOption>(entity =>
        {
            entity.HasKey(e => e.FColorOptionId).HasName("PK__tPartCol__59A0F309F2D3DD66");

            entity.ToTable("tPartColorOption");

            entity.Property(e => e.FColorOptionId).HasColumnName("fColorOptionId");
            entity.Property(e => e.FColorHex)
                .HasMaxLength(7)
                .HasColumnName("fColorHex");
            entity.Property(e => e.FDisplayOrder)
                .HasDefaultValue(0)
                .HasColumnName("fDisplayOrder");
            entity.Property(e => e.FIsDefault)
                .HasDefaultValue(false)
                .HasColumnName("fIsDefault");
            entity.Property(e => e.FOptionName)
                .HasMaxLength(50)
                .HasColumnName("fOptionName");
            entity.Property(e => e.FPartId).HasColumnName("fPartId");
            entity.Property(e => e.FPriceAdjustment)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("fPriceAdjustment");
            entity.Property(e => e.FThumbnail)
                .HasMaxLength(500)
                .HasColumnName("fThumbnail");
        });

        modelBuilder.Entity<TPaymentMethod>(entity =>
        {
            entity.HasKey(e => e.FPaymentMethod).HasName("PK__tPayment__48E89E2AA5648E05");

            entity.ToTable("tPaymentMethod");

            entity.Property(e => e.FPaymentMethod).HasColumnName("fPaymentMethod");
            entity.Property(e => e.FPaymentName)
                .IsRequired()
                .HasMaxLength(15)
                .HasColumnName("fPaymentName");
        });

        modelBuilder.Entity<TPaymentStatus>(entity =>
        {
            entity.HasKey(e => e.FPaymentStatus).HasName("PK__tPayment__8EC1BEDAC4A08106");

            entity.ToTable("tPaymentStatus");

            entity.Property(e => e.FPaymentStatus).HasColumnName("fPaymentStatus");
            entity.Property(e => e.FStatusName)
                .IsRequired()
                .HasMaxLength(15)
                .HasColumnName("fStatusName");
        });

        modelBuilder.Entity<TPickupMethod>(entity =>
        {
            entity.HasKey(e => e.FPickupMethod).HasName("PK__tPickupM__694CB27990CB1B32");

            entity.ToTable("tPickupMethod");

            entity.Property(e => e.FPickupMethod).HasColumnName("fPickupMethod");
            entity.Property(e => e.FPickupMethodName)
                .IsRequired()
                .HasMaxLength(15)
                .HasColumnName("fPickupMethodName");
        });

        modelBuilder.Entity<TProduct>(entity =>
        {
            entity.HasKey(e => e.FProductId).HasName("PK__tProduct__6168D8E0DB1D228A");

            entity.ToTable("tProduct");

            entity.Property(e => e.FProductId).HasColumnName("fProductId");
            entity.Property(e => e.FAssemblyPart)
                .HasMaxLength(255)
                .HasColumnName("fAssemblyPart");
            entity.Property(e => e.FAssemblyRequired).HasColumnName("fAssemblyRequired");
            entity.Property(e => e.FCategoryId).HasColumnName("fCategoryId");
            entity.Property(e => e.FCreateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fCreateTime");
            entity.Property(e => e.FDescription)
                .HasMaxLength(2000)
                .HasColumnName("fDescription");
            entity.Property(e => e.FDiscount).HasColumnName("fDiscount");
            entity.Property(e => e.FName)
                .HasMaxLength(100)
                .HasColumnName("fName");
            entity.Property(e => e.FPstatus).HasColumnName("fPStatus");
            entity.Property(e => e.FUpdateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fUpdateTime");
            entity.Property(e => e.FWarrantyMonth).HasColumnName("fWarrantyMonth");
        });

        modelBuilder.Entity<TProductAsset>(entity =>
        {
            entity.HasKey(e => e.FAssetId).HasName("PK__tProduct__C2AB153D721A8C19");

            entity.ToTable("tProductAsset");

            entity.Property(e => e.FAssetId).HasColumnName("fAssetId");
            entity.Property(e => e.FAssetType)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("fAssetType");
            entity.Property(e => e.FCreateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fCreateTime");
            entity.Property(e => e.FIsPrimary).HasColumnName("fIsPrimary");
            entity.Property(e => e.FMaterialId).HasColumnName("fMaterialId");
            entity.Property(e => e.FMetadateJson).HasColumnName("fMetadateJson");
            entity.Property(e => e.FMimeType)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("fMimeType");
            entity.Property(e => e.FModelId).HasColumnName("fModelId");
            entity.Property(e => e.FPicture)
                .HasMaxLength(100)
                .HasColumnName("fPicture");
            entity.Property(e => e.FPosterUrl)
                .HasMaxLength(500)
                .HasColumnName("fPosterUrl");
            entity.Property(e => e.FProductId).HasColumnName("fProductId");
            entity.Property(e => e.FProductVariantId).HasColumnName("fProductVariantId");
            entity.Property(e => e.FSortOrder).HasColumnName("fSortOrder");
            entity.Property(e => e.FTexturedId).HasColumnName("fTexturedId");
            entity.Property(e => e.FUpdateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fUpdateTime");
            entity.Property(e => e.FUrl)
                .HasMaxLength(500)
                .HasColumnName("fUrl");
        });

        modelBuilder.Entity<TProductPart>(entity =>
        {
            entity.HasKey(e => e.FPartId).HasName("PK__tProduct__62095C7114EEC78E");

            entity.ToTable("tProductPart");

            entity.Property(e => e.FPartId).HasColumnName("fPartId");
            entity.Property(e => e.FDiaplayOrder)
                .HasDefaultValue(0)
                .HasColumnName("fDiaplayOrder");
            entity.Property(e => e.FPartCode)
                .HasMaxLength(50)
                .HasColumnName("fPartCode");
            entity.Property(e => e.FPartName)
                .HasMaxLength(50)
                .HasColumnName("fPartName");
            entity.Property(e => e.FProductId).HasColumnName("fProductId");
        });

        modelBuilder.Entity<TProductReview>(entity =>
        {
            entity.HasKey(e => e.FReviewId);

            entity.ToTable("tProductReview");

            entity.Property(e => e.FReviewId).HasColumnName("fReviewId");
            entity.Property(e => e.FOrderId).HasColumnName("fOrderId");
            entity.Property(e => e.FProductVariantId).HasColumnName("fProductVariantId");
            entity.Property(e => e.FReviewComment)
                .HasMaxLength(50)
                .HasColumnName("fReviewComment");
            entity.Property(e => e.FStar).HasColumnName("fStar");
        });

        modelBuilder.Entity<TProductVariant>(entity =>
        {
            entity.HasKey(e => e.FProductVariantId).HasName("PK__tProduct__F6532C310B7FBBC4");

            entity.ToTable("tProductVariant");

            entity.Property(e => e.FProductVariantId).HasColumnName("fProductVariantId");
            entity.Property(e => e.FColorId).HasColumnName("fColorId");
            entity.Property(e => e.FCost)
                .HasColumnType("decimal(9, 2)")
                .HasColumnName("fCost");
            entity.Property(e => e.FCreateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fCreateTime");
            entity.Property(e => e.FHeight)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("fHeight");
            entity.Property(e => e.FLength)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("fLength");
            entity.Property(e => e.FPrice)
                .HasColumnType("decimal(9, 2)")
                .HasColumnName("fPrice");
            entity.Property(e => e.FProductId).HasColumnName("fProductId");
            entity.Property(e => e.FPstatus).HasColumnName("fPStatus");
            entity.Property(e => e.FSizeLabel)
                .HasMaxLength(50)
                .HasColumnName("fSizeLabel");
            entity.Property(e => e.FSku)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("fSKU");
            entity.Property(e => e.FStock).HasColumnName("fStock");
            entity.Property(e => e.FUpdateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fUpdateTime");
            entity.Property(e => e.FWeight)
                .HasColumnType("decimal(6, 2)")
                .HasColumnName("fWeight");
            entity.Property(e => e.FWidth)
                .HasColumnType("decimal(8, 2)")
                .HasColumnName("fWidth");
        });

        modelBuilder.Entity<TPstatus>(entity =>
        {
            entity.HasKey(e => e.FPstatus).HasName("PK__tPStatus__478B7BFB500F7367");

            entity.ToTable("tPStatus");

            entity.Property(e => e.FPstatus).HasColumnName("fPStatus");
            entity.Property(e => e.FPstatusName)
                .HasMaxLength(20)
                .HasColumnName("fPStatusName");
        });

        modelBuilder.Entity<TRequestStatus>(entity =>
        {
            entity.HasKey(e => e.FStatusId);

            entity.ToTable("tRequestStatus");

            entity.Property(e => e.FStatusId).HasColumnName("fStatusId");
            entity.Property(e => e.FStatus)
                .HasMaxLength(10)
                .HasColumnName("fStatus");
        });

        modelBuilder.Entity<TResponse>(entity =>
        {
            entity.HasKey(e => e.FId);

            entity.ToTable("tResponse");

            entity.Property(e => e.FId).HasColumnName("fId");
            entity.Property(e => e.FDate)
                .HasMaxLength(50)
                .HasColumnName("fDate");
            entity.Property(e => e.FMessage)
                .HasMaxLength(50)
                .HasColumnName("fMessage");
            entity.Property(e => e.FProductId).HasColumnName("fProductId");
            entity.Property(e => e.FUser)
                .HasMaxLength(50)
                .HasColumnName("fUser");
        });

        modelBuilder.Entity<TSalary>(entity =>
        {
            entity.HasKey(e => e.FSalaryId);

            entity.ToTable("tSalary");

            entity.Property(e => e.FSalaryId).HasColumnName("fSalaryId");
            entity.Property(e => e.FBaseSalary)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("fBaseSalary");
            entity.Property(e => e.FBonus)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("fBonus");
            entity.Property(e => e.FDelegateEmployeeId).HasColumnName("fDelegateEmployeeId");
            entity.Property(e => e.FEmployeeId).HasColumnName("fEmployeeId");
            entity.Property(e => e.FPaymentDate)
                .HasColumnType("datetime")
                .HasColumnName("fPaymentDate");
        });

        modelBuilder.Entity<TStatus>(entity =>
        {
            entity.HasKey(e => e.FStatus);

            entity.ToTable("tStatus");

            entity.Property(e => e.FStatus).HasColumnName("fStatus");
            entity.Property(e => e.FStatusName)
                .HasMaxLength(50)
                .HasColumnName("fStatusName");
        });

        modelBuilder.Entity<TTexture>(entity =>
        {
            entity.HasKey(e => e.FTextureId).HasName("PK__tTexture__8DAFFC86FEB1EFE3");

            entity.ToTable("tTexture");

            entity.Property(e => e.FTextureId).HasColumnName("fTextureId");
            entity.Property(e => e.FTextureName)
                .HasMaxLength(30)
                .HasColumnName("fTextureName");
            entity.Property(e => e.FTextureUrl)
                .HasMaxLength(500)
                .HasColumnName("fTextureUrl");
        });

        modelBuilder.Entity<TTimesheet>(entity =>
        {
            entity.HasKey(e => e.FTimesheetId);

            entity.ToTable("tTimesheet");

            entity.Property(e => e.FTimesheetId).HasColumnName("fTimesheetId");
            entity.Property(e => e.FEmployeeId).HasColumnName("fEmployeeId");
            entity.Property(e => e.FHoursWorked)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("fHoursWorked");
            entity.Property(e => e.FOverTimeHours)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("fOverTimeHours");
            entity.Property(e => e.FStatusId).HasColumnName("fStatusId");
            entity.Property(e => e.FWorkDate)
                .HasColumnType("datetime")
                .HasColumnName("fWorkDate");
        });

        modelBuilder.Entity<TTimesheetStatus>(entity =>
        {
            entity.HasKey(e => e.FStatusId);

            entity.ToTable("tTimesheetStatus");

            entity.Property(e => e.FStatusId).HasColumnName("fStatusId");
            entity.Property(e => e.FSatus)
                .HasMaxLength(10)
                .HasColumnName("fSatus");
        });

        modelBuilder.Entity<TWorkDaily>(entity =>
        {
            entity.HasKey(e => e.FWorkDailyId).HasName("PK__tWorkDai__10102549769FFFB5");

            entity.ToTable("tWorkDaily");

            entity.Property(e => e.FWorkDailyId).HasColumnName("fWorkDailyId");
            entity.Property(e => e.FContent).HasColumnName("fContent");
            entity.Property(e => e.FCreateTime)
                .HasColumnType("datetime")
                .HasColumnName("fCreateTime");
            entity.Property(e => e.FEmployeeId).HasColumnName("fEmployeeId");
            entity.Property(e => e.FStatusId).HasColumnName("fStatusId");
            entity.Property(e => e.FTitle)
                .HasMaxLength(100)
                .HasColumnName("fTitle");
            entity.Property(e => e.FUpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("fUpdatedAt");
            entity.Property(e => e.FUpdatedBy)
                .HasMaxLength(20)
                .HasColumnName("fUpdatedBy");
            entity.Property(e => e.FWorkDate)
                .HasColumnType("datetime")
                .HasColumnName("fWorkDate");
        });

        modelBuilder.Entity<TmessageTemplate>(entity =>
        {
            entity.HasKey(e => e.FtemplateId);

            entity.ToTable("TMessageTemplates");

            entity.Property(e => e.FtemplateId).HasColumnName("FTemplateId");
            entity.Property(e => e.FcontentText)
                .IsRequired()
                .HasColumnName("FContentText");
            entity.Property(e => e.FcreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("FCreatedAt");
            entity.Property(e => e.Fdescription)
                .HasMaxLength(255)
                .HasColumnName("FDescription");
            entity.Property(e => e.Ftitle)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("FTitle");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}