// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TAccount
{
    public int FAccountId { get; set; }

    public int? FMemberId { get; set; }

    public string FEmail { get; set; }

    public string FProvider { get; set; }

    public string FProviderAccountKey { get; set; }

    public string FPasswordSalt { get; set; }

    public string FPasswordFinal { get; set; }

    public DateTime? FEmailVerifiedTime { get; set; }

    public int? FLoginFailureCount { get; set; }

    public DateTime? FLastLoginTime { get; set; }

    public DateTime? FCreatTime { get; set; }

    public DateTime? FUpdateTime { get; set; }
}