// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TAnnouncement
{
    public int FId { get; set; }

    public string FTitle { get; set; }

    public string FMessage { get; set; }

    public DateTime? FStartAt { get; set; }

    public DateTime? FEndAt { get; set; }

    public bool? FIsActive { get; set; }

    public int? FPriority { get; set; }

    public DateTime? FLastUpdated { get; set; }
}