// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TCategory
{
    public int FCategoryId { get; set; }

    public string FName { get; set; }

    public int? FParentCategoryId { get; set; }

    public string FCategoryCode { get; set; }

    public string FDescription { get; set; }

    public string FImageUrl { get; set; }

    public bool? FIsActive { get; set; }

    public int? FSortOrder { get; set; }

    public DateTime? FCreateTime { get; set; }

    public DateTime? FUpdateTime { get; set; }
}