// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TChatRoom
{
    public int FChatRoomId { get; set; }

    public int? FMemberId { get; set; }

    public string FVisitorKey { get; set; }

    public string FChannel { get; set; }

    public string FStatus { get; set; }

    public int? FEmployeeId { get; set; }

    public DateTime? FCreatedAt { get; set; }

    public DateTime? FFirstMessageAt { get; set; }

    public DateTime? FLastMessageAt { get; set; }

    public DateTime? FClosedAt { get; set; }

    public int? FIsBotActive { get; set; }

    public string FBotStateJson { get; set; }

    // 🌼 導覽屬性（多對一）
    public virtual TMember? FMember { get; set; }  // ✔ 導覽屬性（指向 TMember）
    // 🌼 導覽屬性（一對多）
    public virtual ICollection<TMessage> Messages { get; set; } = new List<TMessage>();
}