// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TCheckinRecord
{
    public int FCheckinRecordId { get; set; }

    public int? FEmployeeId { get; set; }

    public string FItem { get; set; }

    public decimal? FLongitude { get; set; }

    public decimal? FLatitude { get; set; }

    public DateTime? FCheckinTime { get; set; }

    public string FAddress { get; set; }

    public int? FRediusMeters { get; set; }

    public string FRemark { get; set; }
}