// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TEmployee
{
    public int FEmployeeId { get; set; }

    public string FName { get; set; }

    public string FPhone { get; set; }

    public string FEmail { get; set; }

    public string FHeadShot { get; set; }

    public int? FGender { get; set; }

    public string FBloodType { get; set; }

    public DateOnly? FHireDate { get; set; }

    public int? FRoleId { get; set; }

    public int? FStatusId { get; set; }

    public string FAccount { get; set; }

    public string FPasswords { get; set; }

    public DateTime? FLoginTime { get; set; }

    public DateTime? FChangePasswordTime { get; set; }
}