// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TExternalLogin
{
    public int FExternalLoginId { get; set; }

    public int FMemberId { get; set; }

    public string FProvider { get; set; }

    public string FProviderUserId { get; set; }

    public string FEmail { get; set; }

    public string FDisplayName { get; set; }

    public string FAvatarUrl { get; set; }

    public DateTime FCreateTime { get; set; }

    public DateTime FUpdateTime { get; set; }

    public virtual TMember FMember { get; set; }
}