// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TGender
{
    public int FGenderId { get; set; }

    public string FGenderName { get; set; }
}