// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TLeave
{
    public int FLeaveId { get; set; }

    public int? FEmployeeId { get; set; }

    public string FLeaveType { get; set; }

    public string FPicture { get; set; }

    public DateTime? FStartDate { get; set; }

    public DateTime? FEndDate { get; set; }
}