// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TMaterial
{
    public int FMaterialId { get; set; }

    public string FMarterialName { get; set; }

    public string FDescription { get; set; }
}