// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TMember
{
    public int FMemberId { get; set; }

    public string FName { get; set; }

    public string FDisplayName { get; set; }

    public int? FGender { get; set; }

    public string FPhone { get; set; }

    public DateOnly? FBirthDate { get; set; }

    public string FAddress { get; set; }

    public string FMemberImage { get; set; }

    public int? FLeveId { get; set; }

    public int? FMoneySum { get; set; }

    public int? FStatus { get; set; }

    public DateTime? FCreatTime { get; set; }

    public DateTime? FUpdateTime { get; set; }
}