// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

/// <summary>
/// TMessage = 只是對應資料庫的欄位而已  model對應資料庫
/// </summary>
public partial class TMessage
{
    public int FMessagesId { get; set; }

    public int? FChatRoomId { get; set; }

    public string FSenderType { get; set; }

    public string FSenderId { get; set; }

    public string FContent { get; set; }

    public string FContentType { get; set; }

    public string FContentJson { get; set; }

    public int? FParentMessageId { get; set; }

    public string FMetaJson { get; set; }

    public DateTime? FCreatedAt { get; set; }
}