// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TOrderDetail
{
    public int FOrderId { get; set; }

    public int FProductVariantId { get; set; }

    public int FIsDeleted { get; set; }

    public decimal FUnitPrice { get; set; }

    public int FQuantity { get; set; }
}