// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TProductReview
{
    public int FReviewId { get; set; }

    public int? FOrderId { get; set; }

    public int? FProductVariantId { get; set; }

    public int? FStar { get; set; }

    public string FReviewComment { get; set; }
}