// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TProduct
{
    public int FProductId { get; set; }

    public string FName { get; set; }

    public int? FCategoryId { get; set; }

    public int? FWarrantyMonth { get; set; }

    public string FDescription { get; set; }

    public bool? FAssemblyRequired { get; set; }

    public string FAssemblyPart { get; set; }

    public int? FDiscount { get; set; }

    public int? FPstatus { get; set; }

    public DateTime? FCreateTime { get; set; }

    public DateTime? FUpdateTime { get; set; }
}