// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TProductAsset
{
    public int FAssetId { get; set; }

    public int? FProductId { get; set; }

    public int? FProductVariantId { get; set; }

    public string FPicture { get; set; }

    public string FAssetType { get; set; }

    public string FMimeType { get; set; }

    public string FUrl { get; set; }

    public int? FMaterialId { get; set; }

    public int? FTexturedId { get; set; }

    public int? FModelId { get; set; }

    public string FPosterUrl { get; set; }

    public bool? FIsPrimary { get; set; }

    public int? FSortOrder { get; set; }

    public string FMetadateJson { get; set; }

    public DateTime? FCreateTime { get; set; }

    public DateTime? FUpdateTime { get; set; }
}