// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TProductPart
{
    public int FPartId { get; set; }

    public int? FProductId { get; set; }

    public string FPartName { get; set; }

    public string FPartCode { get; set; }

    public int? FDiaplayOrder { get; set; }
}