// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TRequestStatus
{
    public int FStatusId { get; set; }

    public string FStatus { get; set; }
}