// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TResponse
{
    public int FId { get; set; }

    public string FDate { get; set; }

    public int? FProductId { get; set; }

    public string FUser { get; set; }

    public string FMessage { get; set; }
}