// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TSalary
{
    public int FSalaryId { get; set; }

    public int? FEmployeeId { get; set; }

    public int? FDelegateEmployeeId { get; set; }

    public decimal? FBaseSalary { get; set; }

    public decimal? FBonus { get; set; }

    public DateTime? FPaymentDate { get; set; }
}