// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GraduationProject.Models;

public partial class TWorkDaily
{
    public int FWorkDailyId { get; set; }

    public int? FEmployeeId { get; set; }

    public DateTime? FWorkDate { get; set; }

    public string FTitle { get; set; }

    public string FContent { get; set; }

    public int? FStatusId { get; set; }

    public DateTime? FCreateTime { get; set; }

    public DateTime? FUpdatedAt { get; set; }

    public string FUpdatedBy { get; set; }
}