// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TBrowsingHistory
{
    public int FBrowsingHistoryId { get; set; }

    public int? FMemderId { get; set; }

    public int? FProductId { get; set; }

    public DateTime? FBrowsingTime { get; set; }
}