// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TCart
{
    public int FCartId { get; set; }

    public string FDate { get; set; }

    public int FIsDeleted { get; set; }

    public int FIsCheckOut { get; set; }

    public int FMemberId { get; set; }

    public decimal FTotalPrice { get; set; }
}