// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TCartItem
{
    public int FCartItemId { get; set; }

    public int FCartId { get; set; }

    public int FIsDeleted { get; set; }

    public int FProductVariantId { get; set; }

    public int FQuantity { get; set; }

    public decimal FUnitPrice { get; set; }

    public decimal FSubtotal { get; set; }
}