// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TColorOptionTexture
{
    public int FTextureId { get; set; }

    public int? FColorOptionId { get; set; }

    public string FTextureType { get; set; }

    public string FFilePath { get; set; }

    public string FTiling { get; set; }
}