// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TColor
{
    public int FColorId { get; set; }

    public string FColorName { get; set; }

    public string FColorCode { get; set; }

    public string FColorHex { get; set; }

    public string FThumbnail { get; set; }
}