// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TDeliveryStatus
{
    public int FDeliveryStatus { get; set; }

    public string FDeliveryStatusName { get; set; }
}