// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TEmailVerification
{
    public int FEmailVerificationId { get; set; }

    public string FEmail { get; set; }

    public string FCode { get; set; }

    public DateTime FExpireTime { get; set; }

    public bool FIsUsed { get; set; }

    public DateTime FCreateTime { get; set; }
}