// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TEmployeePasswordReset
{
    public int FResetId { get; set; }

    public int? FEmployeeId { get; set; }

    public string FToken { get; set; }

    public DateTime? FExpiresAt { get; set; }

    public DateTime? FUsedAt { get; set; }

    public DateTime? FCreatedAt { get; set; }
}