// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TLevel
{
    public int FLevelId { get; set; }

    public string FLevelName { get; set; }

    public int? FUpgradeRules { get; set; }

    public decimal? FDiscount { get; set; }
}