// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TmessageTemplate
{
    public int FtemplateId { get; set; }

    public string Ftitle { get; set; }

    public string Fdescription { get; set; }

    public string FcontentText { get; set; }

    public DateTime FcreatedAt { get; set; }
}