// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TModel
{
    public int FModelId { get; set; }

    public string FModelName { get; set; }

    public string FModelUrl { get; set; }
}