// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TorderStatusHistory
{
    public int FHistoryId { get; set; }

    public int FOrderId { get; set; }

    public int FStatusId { get; set; }

    public DateTime FChangeTime { get; set; }

    public int? FEmployeeId { get; set; }
}