// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TOrder
{
    public int FOrderId { get; set; }

    public int FIsDeleted { get; set; }

    public int FMemberId { get; set; }

    public int? FEmployeeId { get; set; }

    public decimal FTotalPrice { get; set; }

    public decimal? FDiscount { get; set; }

    public string FTaxNo { get; set; }

    public DateTime FOrderTime { get; set; }

    public int FOrderStatus { get; set; }

    public int FPaymentMethod { get; set; }

    public int FPaymentStatus { get; set; }

    public DateTime? FPaymentTime { get; set; }

    public int FPickupMethod { get; set; }

    public int FDeliveryStatus { get; set; }

    public string FDeliveryAddress { get; set; }

    public decimal? FShippingCost { get; set; }

    public DateTime? FDeliveryTime { get; set; }

    public int? FLogisticsProvider { get; set; }

    public DateTime? FOrderCompletionTime { get; set; }

    public string FNote { get; set; }
}