// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TPartColorOption
{
    public int FColorOptionId { get; set; }

    public int? FPartId { get; set; }

    public string FOptionName { get; set; }

    public string FColorHex { get; set; }

    public string FThumbnail { get; set; }

    public decimal? FPriceAdjustment { get; set; }

    public bool? FIsDefault { get; set; }

    public int? FDisplayOrder { get; set; }
}