// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TPaymentMethod
{
    public int FPaymentMethod { get; set; }

    public string FPaymentName { get; set; }
}