// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TProductPbrtexture
{
    public int FProductPbrid { get; set; }

    public int? FProductId { get; set; }

    public int? FProductVariantId { get; set; }

    public string FTextureType { get; set; }

    public string FTextureUrl { get; set; }

    public DateTime? FCreateTime { get; set; }
}