// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TShoppingCart
{
    public int FId { get; set; }

    public string FDate { get; set; }

    public int FIsDeleted { get; set; }

    public int FCustomerId { get; set; }

    public int FProductVariantId { get; set; }

    public int FCount { get; set; }

    public decimal FPrice { get; set; }
}