// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TTexture
{
    public int FTextureId { get; set; }

    public string FTextureName { get; set; }

    public string FTextureUrl { get; set; }
}