// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TTimesheetStatus
{
    public int FStatusId { get; set; }

    public string FSatus { get; set; }
}