// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TTimesheet
{
    public int FTimesheetId { get; set; }

    public int? FEmployeeId { get; set; }

    public DateTime? FWorkDate { get; set; }

    public decimal? FHoursWorked { get; set; }

    public decimal? FOverTimeHours { get; set; }

    public int? FStatusId { get; set; }
}