// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProject.Models;

public partial class TUserEvent
{
    public long FEventId { get; set; }

    public int? FUserId { get; set; }

    public string FSessionId { get; set; }

    public int? FProductId { get; set; }

    public int? FProductVariantId { get; set; }

    public int FEventType { get; set; }

    public int? FDwellSec { get; set; }

    public DateTime FOccurredAt { get; set; }
}